service: s3-file-uploader

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  
custom:
  fileUploadBucket: ${self:service}-bucket-${self:provider.stage}

resources:
  Resources:
    FileUploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucket}
        AccessControl: PublicRead